# Load offline release
- name: Load dependencies for an Allspark release
  hosts: all
  roles:
  - { role: download, force_download: true }
  tasks:
  - name: Creating release directory
    file:
      state: directory
      path: "{{ allspark_release_tmp_directory }}"

  - name: Extract release assets
    unarchive:
      src: "{{ allspark_release_destination }}"
      dest: "{{ allspark_release_tmp_directory }}"

  - name: Importing Docker images
    docker_image:
      state: present
      load_path: "{{ allspark_release_tmp_directory }}/images/{{ item | b64encode }}.tar"
      name: "{{ downloads[item].image }}:{{ downloads[item].tag }}"
    with_items: "{{ downloads.keys() | list }}"

  - name: Creating Jenkins plugins volume
    docker_volume:
      name: "allspark_jenkins_plugins"
    when: allspark_jenkins.enabled and allspark_jenkins.import_plugins

  - name: Importing Jenkins volume
    docker_container:
      name: volume_importer
      image: "{{ downloads.volumerize.image }}:{{ downloads.volumerize.tag }}"
      volumes:
        - allspark_jenkins_plugins:/source
        - "{{ allspark_release_tmp_directory }}/dependencies/jenkins_plugins:/backup"
      env:
        VOLUMERIZE_SOURCE: /source
        VOLUMERIZE_TARGET: file:///backup
      command: restore
    when: allspark_jenkins.enabled and allspark_jenkins.import_plugins
