---
- name: restart_gitlab
  command: docker restart gitlab

- name: reconfigure_gitlab
  command: >-
    docker exec gitlab bash -c '
    set -xe;
    gitlab-ctl reconfigure;
    '
  register: gitlab_reconfigure
  until: gitlab_reconfigure.rc == 0
  retries: 10
  delay: 30

- name: migrate_gitlab
  command: >-
    docker exec gitlab bash -c '
    set -xe;
    gitlab-rake db:migrate;
    '
  register: gitlab_migrate
  until: gitlab_migrate.rc == 0
  retries: 10
  delay: 30

- name: change_gitlab_root_password
  command: |
    docker exec gitlab bash -c '
    set -xe;
    echo "
      user = User.where(id: 1).first;
      user.password = File.read(\"/run/secrets/admin_password.txt\").strip;
      user.password_confirmation = File.read(\"/run/secrets/admin_password.txt\").strip;
      user.save!
    " | gitlab-rails console production
    '
  register: gitlab_root_pw_change
  until: gitlab_root_pw_change.rc == 0
  retries: 10
  delay: 30
