- name: send [Pip] Requirements to remote server
  copy:
    src: files/requirements.txt
    dest: "{{ allspark_root_directory }}/config/pip-requirements.txt"

- name: Installing python libraries using requirements file
  pip:
    requirements: "{{ allspark_root_directory }}/config/pip-requirements.txt"
    extra_args: --user
