---


- name: "{{ ansible_distribution }}-{{ ansible_distribution_major_version }} {{ ansible_distribution_release }} - Install Specific OS Family dependency"
  include_tasks: "{{ ansible_os_family }}.yml"

- name: "{{ ansible_distribution }}-{{ ansible_distribution_major_version }} {{ ansible_distribution_release }} - Add user to docker group"
  user:
    name: "{{ ansible_user }}"
    groups: docker
    append: true
  register: user_task
  become: yes

# - name: Reset ssh connection
#   meta: reset_connection
#   when: user_task is changed
#   failed_when: false

# Below is an ugly hack, because of an issue with
# `meta: reset_connection`:
## ERROR! Cannot reset connection
## b'Control socket connect(/home/$USER/.ansible/cp/276d6f8b70): No such file or directory\r\n'
# So we use this trick to force ansible to reconnect
- name: "{{ ansible_distribution }}-{{ ansible_distribution_major_version }} {{ ansible_distribution_release }} - Remove cp dir to force ssh reconnection"
  file:
    path: ~/.ansible/cp
    state: absent
  delegate_to: localhost
  changed_when: false
  when: user_task is changed

- name: FS - Ensuring Allspark directory
  file:
    path: "{{ allspark_root_directory }}"
    state: "directory"
  become: true

- name: FS - Ensuring Allspark directory owner
  file:
    path: "{{ allspark_root_directory }}"
    owner: "{{ ansible_user }}"
  become: true
