---


- name: "{{ ansible_distribution }}-{{ ansible_distribution_major_version }} {{ ansible_distribution_release }} - yum - EPEL repository enabled ? - Only for CentOS/RedHat"
  stat: path={{ allspark_epel_repo_file }}
  register: repo
  become: yes

- name: "{{ ansible_distribution }}-{{ ansible_distribution_major_version }} {{ ansible_distribution_release }} - Import EPEL GPG key"
  rpm_key:
    key: "{{ allspark_epel_gpg_url }}"
    state: present
  become: yes
  when:
    - ansible_distribution != "Fedora"

- name: "{{ ansible_distribution }}-{{ ansible_distribution_major_version }} {{ ansible_distribution_release }} - Install EPEL repository"
  yum:
    name: "{{ allspark_epel_repo_url }}"
    state: present
  become: yes
  when:
    - not repo.stat.exists
    - ansible_distribution != "Fedora"

- name: "{{ ansible_distribution }}-{{ ansible_distribution_major_version }} {{ ansible_distribution_release }} - Install prerequisite for docker"
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - yum-utils
    - lvm2
    - python-pip
  become: yes

- name: "{{ ansible_distribution }}-{{ ansible_distribution_major_version }} {{ ansible_distribution_release }} - Install Storage driver for {{ ansible_distribution }} is < 7.4"
  package:
    name: device-mapper-persistent-data
    state: present
  become: yes
  when:
    - ansible_distribution_version is version('7.4', '<')
    - ansible_distribution != "Fedora"

- name: "{{ ansible_distribution }}-{{ ansible_distribution_major_version }} {{ ansible_distribution_release }} - Add Docker repo - Only for CentOS/RedHat"
  get_url:
    url: "{{ allspark_redhat_docker_repo }}"
    dest: "{{ allspark_docker_repo_file }}"
  become: yes
  when:
    - ansible_distribution != "Fedora"

- name: "{{ ansible_distribution }}-{{ ansible_distribution_major_version }} {{ ansible_distribution_release }} - Install Specific OS Release dependency"
  include_tasks: "{{ ansible_distribution }}-{{ ansible_distribution_major_version}}.yml"
  when:
    - ansible_distribution != "CentOS" and ansible_distribution != "RedHat"

# Older versions of Docker are the same on CentOS/RedHat/Fedora
# CentOS : https://docs.docker.com/install/linux/docker-ce/centos/
# RedHat : The community use https://docs.docker.com/install/linux/docker-ce/centos/ for Redhat
#          Normally Redhat support only Docker-ee see : https://docs.docker.com/install/linux/docker-ee/rhel/#prerequisites
# Fedora: https://docs.docker.com/install/linux/docker-ce/fedora/#prerequisites

- name: "{{ ansible_distribution }}-{{ ansible_distribution_major_version }} {{ ansible_distribution_release }} - Ensure dependencies are installed"
  package:
    name: "{{ item }}"
    state: absent
  with_items:
    - docker
    - docker-common
    - docker-engine
    - docker-client
    - docker-client-latest
    - docker-latest
    - docker-latest-logrotate
    - docker-logrotate
  become: yes

- name: "{{ ansible_distribution }}-{{ ansible_distribution_major_version }} {{ ansible_distribution_release }} - Install Docker Community Edition"
  package:
    name: "docker-ce-{{ allspark_docker_version }}*"
    state: present
  become: yes

- name: "{{ ansible_distribution }}-{{ ansible_distribution_major_version }} {{ ansible_distribution_release }} - Start Docker service"
  systemd:
    name: docker
    state: started
    enabled: yes
  become: yes
